[package]
name = "webpassy"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
sha1 = "0.6.0"
base64 = "~0.6.0"

[profile.release]
lto = true
